### ISSUE TITLE
In which DataBase, we create the Plesk table?

### ISSUE THREAD

**Issue by senejani** [megoRU/Plesk_Auto_Update_Trial_Key#3]
## Create table in MySQL:

In which DataBase?
 
```
CREATE TABLE `Plesk` (
  `id` int(6) NOT NULL AUTO_INCREMENT,
  `text` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `text` (`text`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
```
INSERT INTO Plesk (text) values ("Your Key");
INSERT INTO Plesk (text) values ("Your Key2");
INSERT INTO Plesk (text) values ("Your Key3");
```

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/150109421-73c9e741-f74e-43bc-95fd-7719a2956938.png)

**Comment by senejani** [comment]
Thanks.
Do you mean in a test database?
What's the use of it?
After executing all commands in linux nothing happened?

**Comment by megoRU** [comment]
It`s example

**Comment by megoRU** [comment]
Everything is written in the instructions

**Comment by senejani** [comment]
It is not clear in the instructions.
Can you please explain clearly?
You said to create a table, ok, but where?
In the instructions after running the last command, nothing happened and the license has not been renewed.

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/150180451-799f94c9-f2f6-4e9c-bfed-d8558e07cf06.png)
![image](https://user-images.githubusercontent.com/23276305/150180552-698b4d70-7ed8-4c04-b287-d0af97e45a2f.png)
![image](https://user-images.githubusercontent.com/23276305/150180710-4fdd1310-58c9-4734-85ed-2b2924f38687.png)

Your Key replace from: https://www.plesk.com/plesk-free-download/ 
![image](https://user-images.githubusercontent.com/23276305/150180868-7becc7bc-57fe-4590-9a74-9ab1b420dbf2.png)

Next here
https://github.com/megoRU/Plesk_Auto_Update_Trial_Key#run-on-linux-debianubuntu
