### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by ivan-vilches** [megoRU/Plesk_Auto_Update_Trial_Key#5]
any guide?
INSERT INTO Plesk (text) values ("Your Key");
INSERT INTO Plesk (text) values ("Your Key2");
INSERT INTO Plesk (text) values ("Your Key3");
Those keys where you get?
Thanks

**Comment by megoRU** [comment]
https://github.com/megoRU/Plesk_Auto_Update_Trial_Key#get-free-key
