### ISSUE TITLE
Plesk Trail License Limit

### ISSUE THREAD

**Issue by khalequzzaman17** [megoRU/Plesk_Auto_Update_Trial_Key#6]
They're limiting its users to 3x or less.

**Comment by megoRU** [comment]
I don't quite understand what you mean

**Comment by khalequzzaman17** [comment]
I mean, Plesk is about to close the abuse of free trial licenses. They're going to limit the websites/databases/emails etc. for the free trial license to 3 or less from 26th September 2022

**Comment by megoRU** [comment]
Is there a news item or a link to it somewhere?

**Comment by khalequzzaman17** [comment]
If you have a server with Plesk free trial installed, log into the server as admin, and you'll see the news in the notification bar.

**Comment by bersuit72** [comment]
Hello how are you? Is there any way to eliminate the limits of the trial licenses?

**Comment by peaceanddemocracy** [comment]
yes,limited,the plesk must be lack of money

**Comment by 7054company** [comment]
I found the unlimited license of please for free
https://github.com/7054company/plesk-unlimited-license

**Comment by 7054company** [comment]
We can provide you a plesk license with you partners help

https://github.com/7054company/plesk-unlimited-license
